name: "Run E2E tests on ref"

on:
  workflow_dispatch:
    inputs:
      pr:
        type: string
        required: true
        description: "Pull request number/url to run tests on"
      sha:
        type: string
        required: true
        description: "Commit hash (to validate pr has not changed before the run is started)"

jobs:
  build_backend:
    name: "Build images"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      image-version: ${{ steps.build_image.outputs.image-version }}
    strategy:
      matrix:
        include:
          - image_name: "datalens-control-api"
            bake_target: "dl_control_api"
          - image_name: "datalens-data-api"
            bake_target: "dl_data_api"
    container:
#      image: "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/debian_docker:latest"
      image: "ghcr.io/konstantanxiety/${{ github.event.repository.name }}/debian_docker:latest"
#      image: "ghcr.io/datalens-tech/datalens-backend/debian_docker:latest"
      options: -v /var/run/docker.sock:/var/run/docker.sock
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
#      cr_url: "ghcr.io/${{ github.repository_owner }}"  # TODO this
      cr_url: "ghcr.io/datalens-tech"
    steps:
    - name: Cleanup build folder
      run: |
        rm -rf ./* || true
        rm -rf ./.??* || true
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fix dubious ownership
      run: .github/.scripts/git_config_save_directory.sh
      env:
        REPOSITORY_NAME: ${{ github.event.repository.name }}

    - name: Switch to PR head
      run: gh pr checkout ${{ github.event.inputs.pr }}
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Validate SHA
      run: |
        export HEAD_SHA=$(git rev-parse HEAD)
        export INPUT_SHA="${{ github.event.inputs.sha }}"
        echo $HEAD_SHA
        if [ x"$HEAD_SHA" != x"$INPUT_SHA" ]; then
          echo "The branch was updated since the workflow was triggered, exiting"
          exit 1
        fi

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.cr_url }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build image
      id: build_image
      working-directory: docker_build
      run: |
        bake_target=${{ matrix.bake_target }}
        version="${{ github.event.inputs.sha }}"
        image_version="${version#"v"}"
        image_url="${{ env.cr_url }}/${{ matrix.image_name }}:${image_version}"

        ./run-project-bake "${bake_target}" --set "${bake_target}.tags=${image_url}"

        echo "image-version=${image_version}" >> $GITHUB_OUTPUT

  run_e2e_tests:
    name: "Run E2E tests"
    needs: [ build_backend ]
    uses: datalens-tech/datalens-backend/.github/workflows/run_e2e.yml@main
    with:
      image_version: ${{ needs.build_backend.outputs.image-version }}
    secrets: inherit
